centauri6dof:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint_gear1
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: centauri6dof_arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
    - name: centauri6dof_gripper_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - joint_gear1
        - joint_gear2
  centauri6dof_arm_position_controller:
    type: position_controllers/JointPositionController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint5:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1